image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  # - cleanup
  - build
  - deploy

# cleanup-old-images:
#   stage: cleanup
#   script:
#     - echo "🧹 Удаляем старые образы name_test_bot..."
#     - docker image prune -f || true
#     - docker rmi $(docker images "name_test_bot" --format "{{.ID}}" | tail -n +2) || true
#   only:
#     - main

build-job:
  stage: build
  script:
    - echo "🔧 Собираем новый образ..."
    - docker build -t name_test_bot .

deploy-job:
  stage: deploy
  script:
    - echo "🚀 Запуск docker-compose..."
    - docker-compose down || true
    - docker-compose up -d --build
  only:
    - main
